export const SELECTED_DATE_UPDATED = 'SELECTED_DATE_UPDATED';
export const LAYOUT_UPDATED = 'LAYOUT_UPDATED';

export const UPDATE_NOTE_STATUS = 'UPDATE_NOTE_STATUS';
export const NOTE_CONTENT_FETCHED = 'NOTE_CONTENT_FETCHED';

export const UPDATE_LOCALE = 'UPDATE_LOCALE';
export const UPDATE_THEME = 'UPDATE_THEME';
